### ISSUE TITLE
make coverage

### ISSUE THREAD

**Issue by jakobbossek** [tudo-r/makeR#10]
I extended my makefile with the option `coverage`
`make coverage` then simply loads the the [covr](https://github.com/jimhester/covr) package and executes `package_coverage()`. I would like to add this to makeR. What is your opinion?

**Comment by berndbischl** [comment]
we will remove and delete makeR soon.

Still, possibly a good idea, but please post it for dt and close it here.

**Comment by berndbischl** [comment]
Also, simply help us and implement it there yourself ;-)

**Comment by jakobbossek** [comment]
Ok, did not know about that new tool :+1:
